exports.index = function (req, res) {

    sessionId = req.params.sessionid

    if (sessionId == null || sessionId == undefined)
    {
        sessionId = getRandomSessionID()
    }
    var options = {
        sessionid: sessionId
    }
    res.render('gamefield', options);

    function getRandomSessionID() {

        randomData =
            [
                [
                    "Chandler"
                ],
                [
                    "Malik"
                ],
                [
                    "Florence"
                ],
                [
                    "Shoshana"
                ],
                [
                    "Ori"
                ],
                [
                    "Maxwell"
                ],
                [
                    "Zia"
                ],
                [
                    "Laurel"
                ],
                [
                    "Charles"
                ],
                [
                    "Rooney"
                ],
                [
                    "Skyler"
                ],
                [
                    "Emerald"
                ],
                [
                    "Daniel"
                ],
                [
                    "Nash"
                ],
                [
                    "Kaden"
                ],
                [
                    "Jeanette"
                ],
                [
                    "Suki"
                ],
                [
                    "Sebastian"
                ],
                [
                    "Elijah"
                ],
                [
                    "Yoshio"
                ],
                [
                    "Xerxes"
                ],
                [
                    "Cameron"
                ],
                [
                    "Eleanor"
                ],
                [
                    "Dante"
                ],
                [
                    "Octavius"
                ],
                [
                    "Myles"
                ],
                [
                    "Madonna"
                ],
                [
                    "Leila"
                ],
                [
                    "Brock"
                ],
                [
                    "Elvis"
                ],
                [
                    "Yen"
                ],
                [
                    "Unity"
                ],
                [
                    "Kyla"
                ],
                [
                    "Cora"
                ],
                [
                    "Uriel"
                ],
                [
                    "Reed"
                ],
                [
                    "Cole"
                ],
                [
                    "Jacob"
                ],
                [
                    "Dawn"
                ],
                [
                    "Roth"
                ],
                [
                    "Alan"
                ],
                [
                    "Sebastian"
                ],
                [
                    "Chadwick"
                ],
                [
                    "Wing"
                ],
                [
                    "Leigh"
                ],
                [
                    "Echo"
                ],
                [
                    "Kylie"
                ],
                [
                    "Ivan"
                ],
                [
                    "Blaine"
                ],
                [
                    "Allegra"
                ],
                [
                    "Jerome"
                ],
                [
                    "Desiree"
                ],
                [
                    "Amity"
                ],
                [
                    "Lacota"
                ],
                [
                    "Shoshana"
                ],
                [
                    "Jada"
                ],
                [
                    "Nadine"
                ],
                [
                    "Anika"
                ],
                [
                    "Anastasia"
                ],
                [
                    "Callie"
                ],
                [
                    "Regan"
                ],
                [
                    "Darius"
                ],
                [
                    "Aphrodite"
                ],
                [
                    "Charlotte"
                ],
                [
                    "George"
                ],
                [
                    "Kimberly"
                ],
                [
                    "Hannah"
                ],
                [
                    "Jaden"
                ],
                [
                    "Shannon"
                ],
                [
                    "Ima"
                ],
                [
                    "Nathan"
                ],
                [
                    "Paki"
                ],
                [
                    "Isabelle"
                ],
                [
                    "Kyra"
                ],
                [
                    "Demetrius"
                ],
                [
                    "Abel"
                ],
                [
                    "Kirestin"
                ],
                [
                    "Levi"
                ],
                [
                    "Debra"
                ],
                [
                    "Chadwick"
                ],
                [
                    "Allistair"
                ],
                [
                    "Shannon"
                ],
                [
                    "Yvette"
                ],
                [
                    "Keith"
                ],
                [
                    "Dillon"
                ],
                [
                    "Candace"
                ],
                [
                    "Ignatius"
                ],
                [
                    "Castor"
                ],
                [
                    "Daquan"
                ],
                [
                    "Bradley"
                ],
                [
                    "Lydia"
                ],
                [
                    "Ira"
                ],
                [
                    "Lacota"
                ],
                [
                    "Jana"
                ],
                [
                    "Patience"
                ],
                [
                    "Irma"
                ],
                [
                    "Steven"
                ],
                [
                    "Dean"
                ],
                [
                    "Rae"
                ],
                [
                    "Cally"
                ]
            ]

        return randomData[Math.floor(Math.random()*randomData.length)]


    }
} 